---
version: '3.9'

networks:
  dionysos:
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: image-dev
    ports:
      - 8080:8080
    networks:
      - dionysos
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
    networks:
      - dionysos
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
