version: '3.3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: image-prod
    ports:
      - 8080:8080
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:4.4.7
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_DATABASE=${NEO4J_DATABASE}
      - NEO4J_AUTH=${NEO4J_AUTH}
