---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
linters:
  enable-all: true
  disable:
    - typecheck
