---
name: Docker Build and Push

on:
  push:
    branches: [main, docker-push-patch-2]
    tags:
      - "v*.*.*"

env:
  IMAGE_NAME: brawdunoir/dionysos-server

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install cosign
        uses: sigstore/cosign-installer@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          target: image-prod
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        if: ${{ github.ref == 'refs/heads/dev' }}
        with:
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          username: ${{secrets.USER}}
          key: ${{secrets.PRIVATE_SSH_KEY}}
          script: ${{secrets.SCRIPT}}
