---
name: Testing Routes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  launch-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Test Command
        run: docker-compose -f docker-compose_testing.yaml up --build -d && docker-compose exec api go test tests/*