---
name: Go Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  launch-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Command
        uses: actions/checkout@v3
        run: docker-compose -f docker-compose_testing.yaml up --build -d && docker-compose exec -T api go test tests/*